version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  streamlit:
    build: .
    container_name: agent_streamlit
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
    - postgres
    env_file:
      - .env

volumes:
  pgdata: